a=int(input("Enter a number:"))
b=int(input("Enter a second number:"))
print("Add:",a+b)
print("sub:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Modulus:",a%b)
print("Exponentation:",a**b)
print("Floor division:",a//b)
